protected/controllers/GridController.php
<?php
class GridController extends Controller
{
    public $navigation = array();
    protected $view;

    public function __construct($id, $module = null)
    {
        parent::__construct($id, $module);
        if (isset($_GET['view'])) {
            $this->view = $_GET['view'];
        } else {
            throw new CHttpException(400,
                'Некорректный запрос. Не указано имя xml-файла для построения сетки.'
            );
        }
    }

    public function filters()
    {
        return array(
            'accessControl',
            'ajaxOnly +index, search, getChildGrid, save, cardDataGet, insertRow, upload'
        );
    }

    public function accessRules()
    {
        return array(
            array('allow', 'users' => array('@')),
            array('deny', 'users' => array('*'))
        );
    }

    public function actionIndex()
    {
//        $this->navigation = MenuForm::getMenu();
        $model = Controller::loadForm($this->view);
//        $this->render('index', ['model' => $model]);
        $this->renderPartial('index', ['model' => $model], false, true);
    }

    public function actionSearch($ParentView = null)
    {
        $model = Controller::loadForm($this->view, $ParentView,  Yii::app()->request->getPost('ParentID'));
        $model->attributes = Yii::app()->request->getPost('GridForm');
        $response = $model->getSearchResponse();
        $response->send();
    }

    public function actionSearchByID($id){
        $this->navigation = MenuForm::loadData();
        $model = Controller::loadForm($this->view);
        $model->filters['idlist'] = $id;
        $this->render('index', ['model' => $model]);
    }

    public function actionGetChildGrid($jsonFilters, $ParentView, $parentViewID)
    {
        $ParentID = json_decode($jsonFilters, true)['filters']['ParentID'];
        $model = Controller::loadForm($this->view,$ParentView, $ParentID);
        $model->attributes = array('filters' => array('parentid' => $ParentID));
        $response = $model->getGridResponse($parentViewID);
        $response->send();
    }

    public function actionSave($parentView = null, $parentID = null)
    {
        $model = Controller::loadForm($this->view, $parentView, $parentID);
        $response = $model->save();
        $response->send();
    }

    public function actionInsertRow()
    {
        $model = Controller::loadForm($this->view);
        $response = $model->insertRow();
        $response->send();
    }

    public function actionCardDataGet($pk, $tabID, $viewID)
    {
//        $pk = \Chocolate\HTML\ChHtml::ID_KEY;
        $model = Controller::loadForm($this->view);
        $this->renderPartial('//components/_card',
            [
                'card' => $model->getCard($tabID),
                'view' => $this->view,
                'pk' => $pk,
                'viewID' => $viewID,
                'CardElementSettingsCollection' => $model->getCardElementsSettings($tabID)
            ], false, true);
    }

}

protected/controllers/MapController.php
<?php
Yii::import('webroot.protected.controllers.GridController');
class MapController extends GridController
{
    public function actionIndex()
    {
        $model = Controller::loadForm($this->view);
        $this->renderPartial('index', ['model' => $model], false, true);
    }

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

protected/views/map/_map_form.php
<?php
/**
 * @var $model GridForm
 * @var $parentViewID String
 * @var $this Controller
 */
?>
<?php
$formID = uniqid('f');
$gridID = uniqid('g');
$containerID = uniqid('c');
$view = $model->getView();
if($model->getDataFormProperties()->getCreateEmptyProc()){
    $isSupportCreateEmpty = true;
}else{
    $isSupportCreateEmpty = false;
}
$form = $this->beginWidget('CActiveForm', [
    'action' => Yii::app()->createUrl('grid/save', ['view' => $view]),
    'htmlOptions' => [
        'data-id' => $view,
        'id' => $formID,
        'data-parent-id' => isset($parentViewID) ? $parentViewID : null,
        'data-delete-url' => Yii::app()->createUrl('grid/removeRow'),
        'data-refresh-url' => Yii::app()->createUrl('grid/search', ['view' => $view]),
        'data-ajax-add' => $isSupportCreateEmpty,
        'data-save' => Yii::app()->createUrl('grid/save', ['view' => $view]),
        'data-tab-caption' => $model->getCardCollection()->getCaption(),
        'data-parent-pk' => $model->getParentID(),
        'data-card-support' => $model->isCardAllow()
    ]
]);
?>
<?php $this->renderPartial('//components/_menu', ['model' => $model]) ?>
    <section data-id="map">
<!--        <input type="button" value="Развернуть/Cвернуть" id="toggler"/>-->
        <? $this->renderPartial('_yandex_map', ['model' => $model]); ?>
    </section>
<?php $this->endWidget(); ?>

protected/views/map/_yandex_map.php
<?
/**
 * @var $model GridForm
 * @var $this CController
 */
?>
<?
$mapID = uniqid('map');
$recordset = $model->loadData();
$data = json_encode($recordset->rawUrlEncode());
?>

<div class="map" id="<? echo $mapID?>" style="width: 100%; height: 600px"></div>
<?
Yii::app()->clientScript->registerScript('yandex_map', <<<JS
$(function() {
  // здесь код, который должен быть выполнен после загрузки апи

      ymaps.ready(function(){
      /**
* @type {ChMap}
*/
      var ch_map =ChObjectStorage.create($('#' + '$mapID'), 'ChMap');
         ch_map.init(ymaps, '$data');
//var fullScreen = false;
//      $('#toggler').click(toggle);
//
//function toggle () {
//    fullScreen = !fullScreen;
//    if (fullScreen) {
//       $('#' + '$mapID').removeClass('smallMap');
//    } else {
//        $('#' + '$mapID').addClass('smallMap');
//    }
//    console.log( ch_map.map)
//        ch_map.map.container.fitToViewport();
//}
  });
})
JS
,CClientScript::POS_END
)
?>

protected/views/map/index.php
<?php
/**
 * @var $model GridForm,
 * @var $this Controller
 * @var $parentViewID String|null
 */
?>
<?php $tabID = uniqid('tb'); ?>
<div id='<?php echo $tabID ?>'>
    <section class='section-header' data-id="header">
        <?php $this->renderPartial('//grid/_header', ['model' => $model]); ?>
    </section>

    <? if ($model->hasFilters()) : ?>
    <section class='section-filters' data-id="filters">

    <? $this->renderPartial('//components/_filter_form', ['model' => $model]); ?>
        </section>
    <? endif ?>

    <?php
    if ($parentID = $model->getParentID()) {
        $parentAttribute = 'data-parent-id ="' . $parentID . '"';
    } else {
        $parentAttribute = null;
    }
    ?>
    <section class='section-grid' data-id="grid-form" <?php echo $parentAttribute ?>>
        <?php
        $this->renderPartial('_map_form',
            [
                'model' => $model,
                'parentViewID' => $parentViewID,
            ]
        );?>

    </section>
</div>
<script>
    $(function () {
        Chocolate.addTabAndSetActive(
            '<? echo $tabID ?>',
            '<? echo $model->getDataFormProperties()->getWindowCaption()?>'
        );
    })
</script>